### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by olemartinorg** [Leaflet/Leaflet.draw#644]
Hi!

As soon as I'm trying to draw a rectangle, i get this error:

```
TypeError: Cannot read property 'title' of undefined
at NewClass.getActions (http://localhost/Leaflet/Leaflet.draw/leaflet.draw.src.js:3081:43)
at NewClass._createActions (http://localhost/Leaflet/Leaflet.draw/leaflet.draw.src.js:2868:19)
at NewClass._showActionsToolbar (http://localhost/Leaflet/Leaflet.draw/leaflet.draw.src.js:2911:8)
at NewClass._handlerActivated (http://localhost/Leaflet/Leaflet.draw/leaflet.draw.src.js:2851:8)
at NewClass.fire (http://localhost/Leaflet/Leaflet/leaflet.src.js:588:11)
at NewClass.enable (http://localhost/Leaflet/Leaflet.draw/leaflet.draw.src.js:137:8)
at HTMLAnchorElement.handler (http://localhost/Leaflet/Leaflet/leaflet.src.js:9783:14)
at HTMLAnchorElement._super.bugsnag (http://localhost/BugSnag.js:165:42)
```

Using Firefox, but this also happens in (at least) Chrome.

**Comment by olemartinorg** [comment]
Forgot to mention, this occurred after upgrading to 0.4.0 and Leaflet 1.0.1

**Comment by B3nCr** [comment]
I'm not sure you'll get much help without some code to go with that stack trace.

What's happening in bugsnag?

**Comment by olemartinorg** [comment]
The line numbers should match the 0.4.0 tag, so here's the code: https://github.com/Leaflet/Leaflet.draw/blob/v0.4.0/dist/leaflet.draw-src.js#L3081

Bugsnag is a tool that catches bugs (uncaught exceptions and whatnot) in JavaScript so that you can get reports about them without having access to the console in every users browser.. :-) It is not related to the problem here, it is simply what caught the exception and sent it to me.

**Comment by B3nCr** [comment]
Oh i see, sorry. The rectangle tool seems okay in the demos, perhaps you're including some old files somewhere? Sorry I can't be any more help.

**Comment by olemartinorg** [comment]
Huh, allright, I think I know what it is then. I have hacked on some code that adds a balloon/tooltip to every drawing upon creation, so that the user can edit those as well. I'll have to get back to you with some example code that hopefully reproduces the problem. Sorry about my lack of digging (or thinking clearly), I submitted this at the end of my work day.. :-)

**Comment by olemartinorg** [comment]
Ok, I fixed it! My mistake, of course. I had overwritten L.drawLocal with my own object, so that I could have translations for buttons/actions used in Leaflet.draw. I forgot to check that when upgrading to 0.4.0, so i didn't notice that this new version brought with it the L.drawLocal.draw.toolbar.finish.title property.
